version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "AppUsersRestAPI"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13cohvc9n60no"
s3_prefix = "AppUsersRestAPI"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
